dataset2item_feat_fields = {
    'ml-1m': ['item_id', 'movie_title', 'release_year', 'genres'],
    'ml-10m': ['item_id', 'movie_title', 'release_year', 'genres'],
    'Food': ['item_id', 'name', 'submitted_timestamp', 'contributor_id', 'n_steps', 'minutes', 'nutrition', 'tags'],
    'steam': ['product_id', 'app_name', 'developer', 'early_access', 'genres', 'metascore', 'price', 'publisher', 'timestamp', 'sentiment', 'specs', 'tags', 'title'],
    'yelp2022': ['item_id', 'item_name', 'address', 'city', 'state', 'postal_code', 'latitude', 'longitude', 'item_stars', 'item_review_count', 'is_open', 'categories'],
    'Amazon_Toys_and_Games': ['item_id', 'categories', 'average_rating', 'rating_number', 'price'],
    'Amazon_Musical_Instruments': ['item_id', 'categories', 'average_rating', 'rating_number', 'price'],
    'Amazon_Books': ['item_id', 'categories', 'average_rating', 'rating_number', 'price'],
    'Amazon_All_Beauty': ['item_id', 'categories', 'average_rating', 'rating_number', 'price'],
}

dataset2user_feat_fields = {
    'ml-1m': ['user_id', 'gender', 'age', 'occupation', 'zip_code'],
    'ml-10m': ['user_id', 'gender', 'age', 'occupation', 'zip_code'],
    'steam': None,
    'yelp2022': ['user_id', 'user_name', 'user_review_count', 'yelping_since', 'user_useful', 'user_funny', 'user_cool', 'elite', 'fans', 'average_stars', 'compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list', 'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos'],
    'Food': None,
    'Amazon_Toys_and_Games': None,
    'Amazon_Musical_Instruments': None,
    'Amazon_Books': None,
    'Amazon_All_Beauty': None,
}

dataset2inter_feat_fields = {
    'ml-1m': ['user_id', 'item_id', 'rating', 'timestamp'],
    'ml-10m': ['user_id', 'item_id', 'rating', 'timestamp'],
    'steam': ['user_id', 'play_hours', 'products', 'product_id', 'page_order', 'timestamp', 'early_access', 'page', 'found_funny', 'compensation', 'times'],
    'yelp2022': ['user_id', 'item_id', 'rating', 'timestamp', 'useful', 'funny', 'cool', 'review_id'],
    'Food': ['user_id', 'item_id', 'rating', 'timestamp'],
    'Amazon_Toys_and_Games': ['user_id', 'item_id', 'rating', 'timestamp'],
    'Amazon_Musical_Instruments': ['user_id', 'item_id', 'rating', 'timestamp'],
    'Amazon_Books': ['user_id', 'item_id', 'rating', 'timestamp'],
    'Amazon_All_Beauty': ['user_id', 'item_id', 'rating', 'timestamp'],
}

dataset_feat_alias = {
    'ml-1m': {
        'occupation': {
            '[PAD]': '[PAD]',
            '0':  'other or not specified',
            '1':  'academic/educator',
            '2':  'artist',
            '3':  'clerical/admin',
            '4':  'college/grad student',
            '5':  'customer service',
            '6':  'doctor/health care',
            '7':  'executive/managerial',
            '8':  'farmer',
            '9':  'homemaker',
            '10': 'K-12 student',
            '11': 'lawyer',
            '12': 'programmer',
            '13': 'retired',
            '14': 'sales/marketing',
            '15': 'scientist',
            '16': 'self-employed',
            '17': 'technician/engineer',
            '18': 'tradesman/craftsman',
            '19': 'unemployed',
            '20': 'writer',
        },
        'gender': {
            '[PAD]': '[PAD]',
            'F': 'female',
            'M': 'male',
        },
    },
    'ml-10m': {
        'occupation': {
            '[PAD]': '[PAD]',
            '0':  'other or not specified',
            '1':  'academic/educator',
            '2':  'artist',
            '3':  'clerical/admin',
            '4':  'college/grad student',
            '5':  'customer service',
            '6':  'doctor/health care',
            '7':  'executive/managerial',
            '8':  'farmer',
            '9':  'homemaker',
            '10': 'K-12 student',
            '11': 'lawyer',
            '12': 'programmer',
            '13': 'retired',
            '14': 'sales/marketing',
            '15': 'scientist',
            '16': 'self-employed',
            '17': 'technician/engineer',
            '18': 'tradesman/craftsman',
            '19': 'unemployed',
            '20': 'writer',
        },
        'gender': {
            '[PAD]': '[PAD]',
            'F': 'female',
            'M': 'male',
        },
    },
    'steam': {},
    'yelp2022': {},
    'Food': {},
    'Amazon_Toys_and_Games': {},
    'Amazon_Musical_Instruments': {},
    'Amazon_Books': {},
    'Amazon_All_Beauty': {},
}

dataset_rating_scale = {
    'ml-1m': 5,
    'ml-10m': 5,
    'yelp2022': 5,
    'Food': 5,
    'Amazon_Toys_and_Games': 5,
    'Amazon_Musical_Instruments': 5,
    'Amazon_Books': 5,
    'Amazon_All_Beauty': 5,
}

# TODO: add reviews, etc.